robot-name project done
mila-klimovich/javascript pull request #5
Opened 2024-03-04 17:06 UTC by mila-klimovich

2024-03-04 19:02 UTC, burtovoy requested changes

2024-03-04 19:02 UTC, burtovoy commented on robot_name/robot-name.js
> +    this.pName = String.fromCharCode(Math.floor(Math.random() * (90 - 65 + 1)) + 65)
Нужно разбить на несколько строк – слишком длинная конструкция

2024-03-04 19:02 UTC, burtovoy commented on robot_name/robot-name.js
> +      this.pName = String.fromCharCode(Math.floor(Math.random() * (90 - 65 + 1)) + 65)
Дублирование с 3-й строчкой – вынести в функцию

2024-03-04 19:08 UTC, mila-klimovich commented on robot_name/robot-name.js
> +      this.pName = String.fromCharCode(Math.floor(Math.random() * (90 - 65 + 1)) + 65)
Вопрос: я прямо в этом же PL вношу правки и снова запрашиваю ревью? Или вношу правки у себя и открываю новый PL?

2024-03-04 19:16 UTC, burtovoy commented on robot_name/robot-name.js
> +      this.pName = String.fromCharCode(Math.floor(Math.random() * (90 - 65 + 1)) + 65)
Да, в этом и снова запросить ревью

2024-03-04 21:24 UTC, mila-klimovich commented
а я не знаю, как это делать :О
Сделала как нагуглила) сделала новый комит, попросила еще раз ревью и нажала resolve conversation, последнее не знаю, надо было ли.
Я коммит вижу, но всё равно горит changes requested.
Проверь, пожалуйста, ну и сами изменения тоже. Так норм я разбила по функциям или намельчила? 
@burtovoy

2024-03-05 18:29 UTC, burtovoy commented
Ништяк, стало лучше

2024-03-05 18:29 UTC, merged